### PR TITLE
git: added .env to .gitignore

### PR DESCRIPTION
**Pull request by Bourkupine**
Closes: #18

### CODE REVIEW

**Review by M-Byte480 — APPROVED** [review]
Hmmmm this is a though one

**Comment by Silver-Golden** [comment]
> Closes #18 

Yeah no this does not close that issue (its more than a one liner)

from #18 :
> Goal of this issue is to use a **library** to allow use of a .env

This is easy to approve if its not closing the issue

**Comment by Bourkupine** [comment]
Should now close #18 @Silver-Golden.

Will send the .env file into the discord

**Review by Silver-Golden — APPROVED** [review]
Looks good to me  
Glad it was just this simple

**Review by Silver-Golden — APPROVED** [review]

**Review by M-Byte480 — APPROVED** [review]

**Pull request merged**
